Documentation/updating developer training
constellation-app/constellation-training pull request #15
Opened 2024-03-06 23:10 UTC by Quasar985

### Prerequisites

- [x] Reviewed the [checklist](CHECKLIST.md)

- [x] Reviewed feedback from the "Sonar Cloud" bot. Note that you have to wait
    for the "CI / Unit Tests") to complete first. Failed Unit tests can be 
    debugged by adding the label "verbose logging" to the GitHub PR.

### Description of the Change

Updated developer training documentation to fix typos, make certain areas easier to follow and reflect code changes to core. 

### Alternate Designs

N/A

### Why Should This Be In Core?

More up to date documentation.

### Benefits

More up to date documentation.

### Possible Drawbacks

Additions and change may themselves have typos.

### Verification Process

Code changes were tested while completing developer training exercises.

### Applicable Issues

https://github.com/constellation-app/constellation/issues/1238

2024-03-12 22:03 UTC, antares1470 requested changes

2024-03-12 22:03 UTC, antares1470 commented on Developer Training/constellation-training-solutions/TrainingSolutions/src/au/gov/asd/tac/constellation/training/solutions/chapter5/PandemicArrangementPlugin.java
>              throw new PluginException(PluginNotificationLevel.ERROR, "Required attributes 'Geo.Latitude' and 'Geo.Longitude' do not exist on this graph!");
Should this error now also say "or" rather than "and"?

2024-03-12 22:03 UTC, antares1470 commented on Developer Training/docs/command_to_make_pdf.txt
> +pandoc .\developer_guide.md -f markdown --listings -H .\developer_guide.tex -s --toc -o Developer_Guide.pdf
this file can probably be removed (there is a github actions job that does the conversion)

2024-03-12 22:03 UTC, antares1470 commented on Developer Training/docs/developer_guide.md
> +![](media/image32.png)
is image30 used at all now or can it be removed? (Perhaps image32 should be renamed image30 to replace the old image)

2024-03-12 23:23 UTC, Delphinus8821 approved these changes
Looks good once the requested changes have been fixed.

It would also be good to make sure the new additions part of the ticket is moved into a new ticket so that these can still be added in the future.

2024-03-13 23:25 UTC, antares1470 approved these changes

2024-03-13 23:30 UTC, merged